services:
  - type: web
    name: Lily-GPT-LineBot
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: GPT_MODEL
        value: gpt-4
      - key: PORT
        value: 3000
